server:
  port: ${SERVER_PORT}

spring:
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED}
    baseline-on-migrate: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL-AUTO}
    show-sql: ${SPRING_JPA_SHOW-SQL}
    database: ${SPRING_JPA_DATABASE}
    database-platform: ${SPRING_JPA_DATABASE-PLATFORM}

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
          starttls:
            enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}

  springdoc:
    api-docs:
      path: ${SPRINGDOC_API-DOCS_PATH}
    swagger-ui:
      path: ${SPRINGDOC_SWAGGER-UI_PATH}
      enabled: ${SPRINGDOC_SWAGGER-UI_ENABLED}

security:
  jwt:
    secret-key: ${SPRING_SECURITY_JWT_SECRET_KEY}


