ALTER TABLE arena_info ADD COLUMN street VARCHAR;
ALTER TABLE arena_info ADD COLUMN city VARCHAR;
ALTER TABLE arena_info ADD COLUMN longitude DOUBLE PRECISION;
ALTER TABLE arena_info ADD COLUMN latitude DOUBLE PRECISION;

ALTER TABLE users ADD COLUMN street VARCHAR;
ALTER TABLE users ADD COLUMN city VARCHAR;
ALTER TABLE users ADD COLUMN longitude DOUBLE PRECISION;
ALTER TABLE users ADD COLUMN latitude DOUBLE PRECISION;
